# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
    #  - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/1-modelo.sql:/docker-entrypoint-initdb.d/1-modelo.sql
      - ./data/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: backend
      POSTGRES_DB: backend

#  backend:
#    build:
##      context: .
#    ports:
##      - 8080:8080
#    environment:
#      PORT: 8080